<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MED100.Models\MED100.Models.csproj" />
    <ProjectReference Include="..\MED100.Common\MED100.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
