<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MED100.Data\MED100.Data.csproj" />
    <ProjectReference Include="..\MED100.Models\MED100.Models.csproj" />
    <ProjectReference Include="..\MED100.Common\MED100.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
